language: java
sudo: required
services:
  - docker
env:
  global:
  - IMAGE_NAME=ruijtendaal/iprwc-api
  - secure: OvYtym2FBbtSv6+H6AuvHsCTSB+f5KwDdsNweMOs519++cHSLWNMtu4m0BHwZkMJS8SuytwTXb1Jivjfm+EqNWc6o8dPCRFopo+P/WQX9UBiA6QV5cvwdRUBw4nC8T4NMNyM9a3+gCSm7FqHXybaKMjVig0lEEf7dUDGRJhw5CExIh1h81bdq+9mEooznggcHuKBFG7f17dRw0ebQejOP4F2nncXKLmsltbH+Q9H96gS1RlgR42epCB74n+fToCc02HzsDbXjbk/F1UGdwT+B1nOWIxoNG51Hza8cv8k4gkCvBQvOAmxInPrnrB31GN4kBi/ET+1E5ZIb/96SNQoQ8Vz2zdMFit2mHvCqqEVzeaE5YBzF4e9gw+r8yA24KVIn+z7e5rQ/Y+rsklgT74FAVr176hicCQMIpw/s+5b9HInPSWbagU+sjhu29JW/8bnRWn0JX45RarAlEBfwZ/lxMN7JMetWLXYtDA6OkOj29xBc+oLOnSOe6SUMpZEwhSCN9FploUBN8WJ6ckWm+nKkViWX4htR2koKzCxpngoJCbRf2w4gWXfj1vrqtDpwIWcjwc/rC4KRY3MjDf2YkFam+/KHOxykRQ6sZxpOkjlsVgS+KgMGCvCvs/29HxZGWL4dhkLM2F6+NhpZI9Tkleg5LRrrQJT7pXv7y+6tbjunR0=
  - secure: AxgR7tImSV+L0cWpEnTU0q1vkiyr6O+jmBR8dNs9E528qKtg1krGzfQusi9UXWQZvqVsMp/am+R+GD/5qCteEbuIM9he8s5261Cwh6p7JaFM2qgVkxc3VhwDjY6BoIaHQ4ukLc72ZlyBuEkVqPiz/0s3t1JeVOhxdwheArkspPpYh8XmOuY4PRgNZM9Gvbb213kfOTluE69V1oaA1mOhnphBv4Q+yswDMB1dDyqWGuR15U6/hL/ksaoCoOxuuq5BLzcKVll+xkxg4lYePGnfnb+6cxfR8+K3x0KR3M2E+GO5HTUsjS88ZvRgcZmHj9i4JUFji+spdMtwwUMQD95dCPEbAu6W0EHBJ+kOHvDvz4aLqWtNOb/TrdvO1ALW9dKJR5r7CJMJmsVmbqUdQMe7ux2049PKo6YufnDoBu1YBI9waYKPCs3Ny1kjZBU5uF1Frh1q8gsii1DqUtA2dsW4ImCEySwqtsBkHxYyqx43y/KjteLfdqFdqkrbUlZ8Nvs0OPN8H3x6qCAyRzD4cgsOdaTKMgCxXnYLFTqdk6kXbMyvhVBaWqiPYvHKTW0r9T35XNfSwtv6nwoBsdJqGnbVPlZZVPKSUCdb+SsT+RBfgXc4A71xp14LQ0lm37XaWZ903Gt9T3pU1u4q5VwjWzKM/yjO/ZM6A3+CqJRkGWPSAb8=

before_script:
  - version=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate "-Dexpression=project.version")
script:
  - docker build --tag "$IMAGE_NAME" .
before_deploy:
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest && docker push "${IMAGE_NAME}:${version}
  on:
    branch: master
