language: java
sudo: required
services:
- docker
env:
  global:
  - IMAGE_NAME=ruijtendaal/iprwc-api
  - REGISTRY_USER=ruijtendaal
  - secure: gSUJm33yznQBlwMClyiLxj0u7f0ggQfOOI5PBkycOOejNhs+OgcVJ/EANyW/KGH/3vT1FTbgRU4o26PaegpVX4V06s0U3w2KNoaO9V5F+vlJk0tSfZtVgWA2lrjuuM9h4GQZk1QBJ0TGYtJPLkOMUkzczfcB2PQVfPdeV8KR6VSmGEt1lscr0fhjZfDTsE//S4aTmoXY98oj4QPgU9Fffo0RawO+YcFmySo0Q+hzew/lMPHABlepXPfexf5OqdSxFFOT+uUlJkaFFTJ60Dq17W4QZWlPGi3ROlJiByxcPzfa/YVbWBp0lsTaq8bkFVjji9aT+wEHiuVEUVbhyV8CUUl4qhSgXP3764Zsz46idmTwrFchz8nNjD4uxygHlD1Z2etOUYvhuNPw1RO4Iu18VS8aZoLMBdmcgDniwdXktkcaZH9ILW6/5ZtSnnA+ZzjJLCZ6DzU+YJzFSXrhnySirrjg+RQKJfFlf2v4ZFjMfBy2VkcXcrXJpeiFftWKzdaIrugDsIJnl+Tf4Lw047XgcOx+17mV8gbnMFqzq+cBis4Sl/v18SeFFLrTKfFFVx+EVDaUOl8truN1iUqLCrIfyPgWlna9bfOOels9BgXcJRNYpPZMRu+EI2dkH0d72iEX0gen/wnDii6oII8ioexCDsUMzvTQ3x8fD7jrK+LjGlM=
before_script:
  - version="$(awk '$2 == "API_VERSION" { print $3; exit }' Dockerfile)"
script:
- mvn clean install
- docker build --tag $IMAGE_NAME:${version} .
before_deploy:
- echo $REGISTRY_PASS | docker login -u $REGISTRY_USER --password-stdin
deploy:
  provider: script
  script: docker push ${IMAGE_NAME}:${version}
  on:
    branch: master