logging:
  level: INFO
  loggers:
    com.rutgeruijtendaal: DEBUG

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: #

  # the password
  password: #

  # the JDBC URL
  url: jdbc:postgresql://db:5432/

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.globally_quoted_identifiers: true

server:
  #  softNofileLimit: 1000
  #  hardNofileLimit: 1000
  type: simple
  connector:
    type: http
    port: 8080
